# Generated by Django 5.2.9 on 2026-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('facebook_icon', models.ImageField(upload_to='photos/socialmedia')),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_icon', models.ImageField(upload_to='photos/socialmedia')),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_icon', models.ImageField(upload_to='photos/socialmedia')),
                ('instagram_url', models.URLField(blank=True)),
                ('email_icon', models.ImageField(upload_to='photos/socialmedia')),
                ('email', models.EmailField(max_length=254)),
                ('footer', models.CharField(max_length=100)),
            ],
        ),
    ]
