# Generated by Django 5.2.9 on 2026-01-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='actress_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/seo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
