# Generated by Django 5.2.9 on 2026-01-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Global Settings', 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='youtube_icon',
        ),
    ]
