# Generated by Django 5.2.9 on 2026-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_actress_name_sitesettings_seo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
