# Generated by Django 5.2.9 on 2026-01-21 23:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Vani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('main_description', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description')),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='photos/about')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description')),
                ('hero_image', models.ImageField(upload_to='photos/homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('main_info', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Main_Info')),
                ('profile', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Profile')),
                ('resume_pic', models.ImageField(upload_to='photos/resume')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='files/resume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description')),
                ('image', models.ImageField(upload_to='photos/about')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_vani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pages.about_vani')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_fullname', models.CharField(max_length=100)),
                ('ref_phone', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='pages.resume')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('language_level', models.PositiveIntegerField(default=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='pages.resume')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='pages.resume')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_level', models.PositiveIntegerField(default=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pages.resume')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
