# Generated by Django 5.2.9 on 2026-01-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['order'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='about_vani',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pages.about_vani'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
