# Generated by Django 5.2.9 on 2026-04-07 12:05

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showreel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='You can use bold, italics, lists and links.', verbose_name='Description')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/showreel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Showreel',
                'verbose_name_plural': 'Showreel',
            },
        ),
        migrations.AlterModelOptions(
            name='about_vani',
            options={'verbose_name': 'About bkp', 'verbose_name_plural': 'About bkp'},
        ),
        migrations.CreateModel(
            name='About_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description')),
                ('image', models.ImageField(upload_to='photos/about')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_vani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'About Vani',
                'verbose_name_plural': 'About Vani',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article_bkp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description')),
                ('image', models.ImageField(upload_to='photos/about')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_vani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_bkp', to='pages.about_vani')),
            ],
            options={
                'verbose_name': 'Article_bkp',
                'verbose_name_plural': 'Articles_bkp',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
