# Generated by Django 5.2.9 on 2026-01-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_article_options_article_about_vani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
    ]
