# Generated by Django 5.2.9 on 2026-04-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_credits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Credits_Category',
        ),
    ]
