# Generated by Django 5.2.9 on 2026-04-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_category_credits_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
    ]
