# Generated by Django 5.2.9 on 2026-01-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(),
        ),
    ]
