# Generated by Django 5.2.9 on 2026-04-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_credits_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits_category',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='credits_category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
