# Generated by Django 5.2.9 on 2026-01-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_homepage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepage'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resume'},
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='pages.resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='pages.resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pages.resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
