# Generated by Django 5.2.9 on 2026-01-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_homepage_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(default='VANISHREE KULKARNI', max_length=100),
            preserve_default=False,
        ),
    ]
