# Generated by Django 5.2.9 on 2026-04-08 16:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_credits_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits_category',
            options={'ordering': ['order'], 'verbose_name': 'Credits Category', 'verbose_name_plural': 'Credits Category'},
        ),
        migrations.AddField(
            model_name='credits_category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
