# Generated by Django 5.2.9 on 2026-04-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_credits_category_options_credits_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'ordering': ['category'], 'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
        migrations.RemoveField(
            model_name='credits',
            name='order',
        ),
    ]
