# Generated by Django 5.2.9 on 2026-01-06 21:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_resume_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='main_info',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Main_Info'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='You can use bold, italics, lists and links.', verbose_name='Profile'),
        ),
    ]
