# Generated by Django 5.2.9 on 2026-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_credits_options_remove_credits_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, help_text='format = 400 x 350', upload_to='photos/homepage'),
        ),
    ]
