# Generated by Django 5.2.9 on 2026-01-13 13:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_vani',
            name='main_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description About Vani', help_text='You can use bold, italics, lists and links.', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_vani',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/about'),
        ),
    ]
