# Generated by Django 5.2.9 on 2026-04-09 13:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='detailed_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='You can use bold, italics, lists and links.', verbose_name='Detailed Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_desktop',
            field=models.ImageField(blank=True, help_text='Pixel / Format = 400 x 350', upload_to='photos/homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_laptop',
            field=models.ImageField(blank=True, help_text='Pixel / Format = 400 x 350', upload_to='photos/homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='You can use bold, italics, lists and links.', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, help_text='Pixel / Format = 400 x 350', upload_to='photos/homepage'),
        ),
    ]
