# Generated by Django 5.2.9 on 2026-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_homepage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_me_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
