# Generated by Django 5.2.9 on 2026-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_homepage_about_me_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image_desktop',
            field=models.ImageField(blank=True, help_text='1920px wide landscape for desktop', upload_to='photos/homepage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image_laptop',
            field=models.ImageField(blank=True, help_text='1280px landscape for laptop', upload_to='photos/homepage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, help_text='768px portrait for mobile', upload_to='photos/homepage'),
        ),
    ]
