# Generated by Django 5.2.9 on 2026-04-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_homepage_hero_image_desktop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_article',
            options={'ordering': ['order'], 'verbose_name': 'Homepage - Article', 'verbose_name_plural': 'Homepage - Articles'},
        ),
        migrations.AddField(
            model_name='showreel',
            name='video_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='showreel',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Paste only the YouTube video ID (11 characters)', max_length=11),
        ),
    ]
