# Generated by Django 5.2.9 on 2026-05-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_about_article_options_showreel_video_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showreel',
            name='video',
        ),
    ]
