# Generated by Django 5.2.9 on 2026-05-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactmessage_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
