server {
    listen 80;
    server_name vanishreekulkarni.in www.vanishreekulkarni.in;

    client_max_body_size 20M;

    # Force HTTPS (Cloudflare Full/Strict compatible)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vanishreekulkarni.in www.vanishreekulkarni.in;

    ssl_certificate /etc/ssl/cloudflare/cert.pem;
    ssl_certificate_key /etc/ssl/cloudflare/key.pem;

    client_max_body_size 20M;

    # STATIC FILES
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # MEDIA FILES
    location /media/ {
        alias /app/media/;
    }

    # MAIN APP
    location / {
        proxy_pass http://web:8000;

        proxy_set_header Host $host;

        # Important for Django behind proxy
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
    }
}