server {
    listen 80;
    server_name vanishreekulkarni.in www.vanishreekulkarni.in;

    client_max_body_size 20M;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vanishreekulkarni.in www.vanishreekulkarni.in;

    ssl_certificate /etc/ssl/cloudflare/cert.pem;
    ssl_certificate_key /etc/ssl/cloudflare/key.pem;

    client_max_body_size 20M;

    # GZIP
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1000;

    # MEDIA FILES ONLY
    location /media/ {
        alias /app/media/;
    }

    # MAIN APP (includes static via WhiteNoise)
    location / {
        proxy_pass http://web:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
    }
}