# Generated by Django 5.2.9 on 2026-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('horror', 'Horror'), ('drama', 'Drama'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('horror', 'Horror'), ('drama', 'Drama'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
