# Generated by Django 5.2.9 on 2026-01-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['content_type', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
