# Generated by Django 5.2.9 on 2026-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_photo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default=1, help_text='Paste only the YouTube video ID (11 characters)', max_length=11),
            preserve_default=False,
        ),
    ]
