# Generated by Django 5.2.9 on 2026-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_remove_video_youtube_url_video_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/gallery'),
        ),
    ]
    
