name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/deploy/vani-portfolio

            echo "Pulling latest code..."
            git pull origin main

            echo "Building & starting containers..."
            docker compose up -d --build

            echo "Waiting for app to be ready..."

            MAX_ATTEMPTS=30
            ATTEMPT=0

            until curl -s http://localhost > /dev/null; do
              ATTEMPT=$((ATTEMPT+1))

              if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
                echo "App failed to start"
                docker compose logs web
                exit 1
              fi

              sleep 2
            done

            echo "App is ready"

            echo "Running migrations..."
            docker compose exec web python manage.py migrate --noinput

            echo "Cleaning unused images..."
            docker system prune -f

            echo "Deployment completed"
          EOF